spring.datasource.url=jdbc:postgresql://localhost:5432/aerolinea_db
spring.datasource.username=aerolinea_user
spring.datasource.password=aerolinea_user
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
