spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/aerolinea_db
#spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres
#spring.datasource.url=jdbc:postgresql://db.qugwbehmepbwwnvtnplx.supabase.co:5432/postgres?user=postgres&password=3wX%r29V#D09

#spring.datasource.username=postgres.pfxfsbqlixaiggmgvmfn
#spring.datasource.password=HMCuDBimhE6giyN2

spring.datasource.username=aerolinea_user.pfxfsbqlixaiggmgvmfn
spring.datasource.password=aerolinea_user

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.properties.hibernate.format_sql=true
# Limita las conexiones que toma HikariCP (por defecto son 10)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2