# =====================================================================
# CONFIGURACIÓN GENERAL DE LA APLICACIÓN (SKYWAY)
# =====================================================================
spring.application.name=SkyWay
server.port=${PORT:8080}
spring.main.web-application-type=servlet
server.servlet.context-path=/

# Inicialización diferida (Lazy): Los Beans se cargan bajo demanda
spring.main.lazy-initialization=true

# Perfil Activo
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}


# =====================================================================
# CONFIGURACIÓN FRONTEND NATIVO (JSF / PRIMEFACES / WELD)
# =====================================================================
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.xhtml
server.error.whitelabel.enabled=true
joinfaces.primefaces.theme=nova-dark

# Aumenta el buffer de renderizado para permitir redirigir si ocurre un error a mitad de página
spring.jpa.open-in-view=true



# Configuraciï¿½n de WebPay
webpay.commerceCode=597055555532
webpay.apiKey=579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C
# WebPay Config (Valores por defecto corresponden al ambiente de integración / pruebas de Transbank)
webpay.integration-type=TEST
webpay.return-path=/webpay/commit


# Mensajes de Error de JSF
label.expired.title=View expired
label.expired.message=The requested page could not be recovered.
label.expired.click-here=Click here to reload the page.

# =====================================================================
# CONFIGURACIÓN SERVICIO MENSAJERÍA (GMAIL SMTP)
# =====================================================================
spring.mail.host=smtp.gmail.com
#spring.mail.port=465
spring.mail.username=cristobalromanzamora13@gmail.com
spring.mail.password=vgeakinstnxqzdkh
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.default-encoding=UTF-8


#spring.mail.port=587
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
