spring.datasource.url=jdbc:postgresql://192.168.100.99:5432/aerolinea_db
#spring.datasource.url=jdbc:postgresql://192.168.100.134:5432/sky_masiva
spring.datasource.username=aerolinea_user
spring.datasource.password=aerolinea_user
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=15
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.pool-name=HikariPool-1

