CREATE TABLE Tarifa (
    ID_TARIFA INT PRIMARY KEY DEFAULT nextval('tarifa_seq'),
    Nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Caracteristica_Tarifa (
    ID_CARACTERISTICA INT PRIMARY KEY DEFAULT nextval('caracteristica_tarifa_seq'),
    Nombre VARCHAR(100) NOT NULL UNIQUE,
    Descripcion TEXT
);

CREATE TABLE Tarifa_Caracteristica (
    ID_TARIFA INT REFERENCES Tarifa(ID_TARIFA) ON DELETE CASCADE,
    ID_CARACTERISTICA INT REFERENCES Caracteristica_Tarifa(ID_CARACTERISTICA) ON DELETE CASCADE,
    Valor VARCHAR(100),
    PRIMARY KEY (ID_TARIFA, ID_CARACTERISTICA)
);
